policyengine_to_taxsim:
  taxsimid:
    variable: taxsimid
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "Record ID"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  year:
    variable: get_year
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "Year"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  state:
    variable: get_state_code
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "State (SOI code)"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  fiitax:
    variable: income_tax
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "Federal IIT Liability"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  siitax:
    variable: state_income_tax
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "State IIT Liability"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  fica:
    variable: na_pe
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "FICA (OADSI and HI, sum of employee AND employer including Additional Medicare Tax)"
    group_order: 1
    full_text_group: "Basic Output"
    group_column: 1
  frate:
    variable: na_pe
    implemented: false
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "Federal Marginal Rate"
    group_order: 2
    full_text_group: "Marginal Rates wrt Weighted Average Earnings"
    group_column: 1
  srate:
    variable: na_pe
    implemented: false
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "State Marginal Rate"
    group_order: 2
    full_text_group: "Marginal Rates wrt Weighted Average Earnings"
    group_column: 1
  ficar:
    variable: na_pe
    implemented: false
    idtl:
      - standard: 0
      - full: 2
    text_description: "FICA rate"
    group_order: 2
    full_text_group: "Marginal Rates wrt Weighted Average Earnings"
    group_column: 1
  tfica:
    variable: taxsim_tfica
    implemented: true
    idtl:
      - standard: 0
      - full: 2
      - full_text: 5
    text_description: "Taxpayer liability for FICA"
    group_order: 2
    full_text_group: "Marginal Rates wrt Weighted Average Earnings"
    group_column: 1
  v10:
    variable: adjusted_gross_income
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Federal AGI"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v11:
    variable: tax_unit_taxable_unemployment_compensation
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "UI in AGI"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v12:
    variable: tax_unit_taxable_social_security
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Social Security in AGI"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v13:
    variable: standard_deduction
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Zero Bracket Amount / Standard Deduction"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v14:
    variable: exemptions
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Personal Exemptions"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v15:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Exemption Phaseout"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v16:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Deduction Phaseout"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v17:
    variable: itemized_taxable_income_deductions
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Itemized Deductions in taxable income"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  qbid:
    variable: qualified_business_income_deduction
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "QBI deduction"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  niit:
    variable: net_investment_income_tax
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Net Investment Income Tax"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v18:
    variable: taxable_income
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Federal Taxable Income"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v19:
    variable: income_tax_main_rates
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Federal Regular Tax"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v20:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Exemption Surtax"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v21:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "General Tax Credit"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v22:
    variable: ctc_value
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Child Tax Credit"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v23:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Reserved"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v24:
    variable: cdcc
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Child Care Credit"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v25:
    variable: eitc
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Earned Income Credit"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v26:
    variable: amt_income
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Income for the Alternative Minimum Tax"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v27:
    variable: alternative_minimum_tax
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "AMT Liability after credit for regular tax and other allowed credits"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v28:
    variable: multiple_variables
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Federal Income Tax Before Credits"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
    variables:
      - income_tax_main_rates
      - capital_gains_tax
  v29:
    variable: taxsim_tfica
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "FICA"
    group_order: 3
    full_text_group: "Federal Tax Calculation"
    group_column: 1
  v30:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "State Household Income"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v31:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "State Rent Expense (imputation for property tax credit)"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v32:
    variable: state_agi
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "32. AGI"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v33:
    variable: na_pe
    implemented: false
    idtl:
      - full: 2
      - full_text: 5
    text_description: "33. Exemptions"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v34:
    variable: state_standard_deduction
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "34. Standard Deduction"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v35:
    variable: state_itemized_deductions
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "35. Itemized Deductions"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v36:
    variable: state_taxable_income
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "36. Taxable Income"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  staxbc:
    variable: state_income_tax_before_non_refundable_credits
    implemented: true
    idtl:
      - full_text: 5
    text_description: "Tax before credits"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v41:
    variable: na_pe
    implemented: false
    idtl:
      - full_text: 5
    text_description: "State Bracket Rate"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v37:
    variable: state_property_tax_credit
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "37. Property Tax Credit"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v38:
    variable: state_cdcc
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "38. Child Care Credit"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v39:
    variable: state_eitc
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "39. EIC"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  sctc:
    variable: state_ctc
    implemented: true
    idtl:
      - full_text: 5
    text_description: "Child Tax Credit"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
  v40:
    variable: multiple_variables
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "40. Total Credits"
    group_order: 4
    full_text_group: "State Tax Calculation"
    group_column: 1
    variables:
      - state_non_refundable_credits
      - state_refundable_credits
  v42:
    variable: na_pe
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "42. Earned Self-Employment Income for FICA"
    group_order: 5
    full_text_group: "TCJA 2018+"
    group_column: 1
  v43:
    variable: na_pe
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Medicare Tax on Unearned Income"
    group_order: 6
    full_text_group: "Additional Medicare Taxes 2013+"
    group_column: 1
  v44:
    variable: multiple_variable
    implemented: true
    idtl:
      - full: 2
    text_description: "44. Medicare Tax on Earnings"
    group_order: 6
    full_text_group: "Additional Medicare Taxes 2013+"
    group_column: 1
    variables:
      - employee_medicare_tax
      - additional_medicare_tax
  actc:
    variable: refundable_ctc
    implemented: false
    idtl:
      - full_text: 5
    text_description: "Refundable Part of CTC"
    group_order: 7
    full_text_group: "Decomposition of Federal Marginal Rate \n (taxpayer earned income) \n Regular Income Tax"
    group_column: 1
  cares:
    variable: recovery_rebate_credit
    implemented: true
    idtl:
      - full: 2
      - full_text: 5
    text_description: "Cares Recovery Rebates"
    group_order: 7
    full_text_group: "Decomposition of Federal Marginal Rate \n (taxpayer earned income) \n Regular Income Tax"
    group_column: 1


taxsim_to_policyengine:
  household_situation:
    families:
      your family:
        members: [ ]
    households:
      your household:
        members: [ ]
        state_name: { }
    marital_units:
      your marital unit:
        members: [ ]
    people: { }
    spm_units:
      your household:
        members: [ ]
    tax_units:
      your tax unit:
        members: [ ]
    additional_tax_units:
      - tax_unit_childcare_expenses:
          - childcare
      - state_use_tax:
          - 'pa'
          - 'nc'
          - 'ca'
          - 'il'
          - 'in'
          - 'ok'
      - de_relief_rebate: 
      - state_sales_tax: 
    additional_income_units:
      - taxable_interest_income:
          - intrec
      - rent:
          - rentpaid
      - qualified_dividend_income:
          - dividends
      - long_term_capital_gains:
          - ltcg
      - self_employment_income:
          - psemp
          - ssemp
      - partnership_s_corp_income:
          - scorp
      - qualified_business_income:
          - pbusinc
      - rental_income:
      - w2_wages_from_qualified_business:
      - business_is_sstb:
      - business_is_qualified:
      - social_security:
      - taxable_private_pension_income:
          - pensions
      - short_term_capital_gains:
          - stcg
      - social_security_retirement:
          - gssi
      - deductible_mortgage_interest:
          - mortgage
      - real_estate_taxes:
          - proptax
      - unemployment_compensation:
          - pui
          - sui

taxsim_input_definition:
  - taxsimid:
      name: "1. Record ID"
  - year:
      name: "2. Tax Year"
  - state:
      name: "3. State Code"
  - mstat:
      name: "4. Marital Status"
      type:
        - single: 1
        - joint: 2
  - page:
      name: "5. Age of primary taxpayer"
      pair: sage
  - dependent_exemption:
      name: "6. Dependent Exemptions"
  - depx:
      name: "8. Number of Dependents"
  - pwages:
      name: "9. Wage and salary income of primary taxpayer"
      pair: swages
  - psemp:
      name: "10. Self-employment income of primary taxpayer"
      pair: ssemp
  - dividends:
      name: "11. Dividend Income"
  - intrec:
      name: "12. Interest Received"
  - stcg:
      name: "13. Short Term Gains"
  - ltcg:
      name: "14. Long Term Gains"
  - otherprop:
      name: "15. Other Property"
  - nonprop:
      name: "16. Other Non-Property"
  - pensions:
      name: "17. Taxable Pensions"
  - gssi:
      name: "18. Gross Social Security"
  - pui:
      name: "19. Tot/Txpy/Spouse UI"
      pair: sui
  - transfers:
      name: "20. Non-taxable Transfers"
  - rentpaid:
      name: "21. Rent Paid"
  - proptax:
      name: "22. Property Taxes Paid"
  - otheritem:
      name: "23. Other Itemized Deds"
  - childcare:
      name: "24. Child Care Expenses"
  - mortgage:
      name: "25. Mortgage Interest"
  - scorp:
      name: "26. S-Corp profits"
  - pbusinc:
      name: "27. Primary and secondary Taxpayer's active QBI"
  - pprofinc:
      name: "28. Primary and secondary taxpayer's Specialized Service Trade or Business service"
