name: Run Tests

on:
  push:
    branches: [main, refactor]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11"]

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install pytest

      - name: Make TAXSIM executables executable (Unix)
        if: runner.os != 'Windows'
        run: chmod +x resources/taxsim35/taxsim35-*.exe

      - name: Run tests
        run: pytest tests/
