name: Debug PR Workflow

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Debug event info
        if: github.event_name == 'pull_request'
        env:
          EVENT_CONTEXT: ${{ toJson(github.event) }}
        run: |
          echo "Pull Request Event Info:"
          echo "$EVENT_CONTEXT"

      - name: Run a simple test
        run: |
          echo "This workflow ran successfully"
          echo "Event name: ${{ github.event_name }}"
          echo "PR number: ${{ github.event.pull_request.number }}"
          echo "PR title: ${{ github.event.pull_request.title }}"
          echo "PR base ref: ${{ github.event.pull_request.base.ref }}"
          echo "PR head ref: ${{ github.event.pull_request.head.ref }}"
